name: assignment_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0-87.0.dev <4.0.0'

dependencies: 
  get: 4.6.6
  dio: 5.3.3
  loading_overlay: 0.3.0
  flutter_spinkit: 5.2.0
  cached_network_image: 3.3.0
  intl: 0.18.1
  pinch_zoom_release_unzoom: ^1.0.1

  test: 1.24.9


  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/news_icon.png
  uses-material-design: true

